from routes.func_ import *
from routes.dashboard import *
from routes.error import *
from routes.user import *
from routes.admin import *
from routes.auth import *
from routes.product import *
from routes.category import *
from routes.invoice import *
from routes.invoice_detail import *
from routes.report import *